import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useQuery } from '@apollo/client'
import {GET_SNAPSHOT} from "../grahpql/operations/queries/getPairInfo";

const inter = Inter({ subsets: ['latin'] })




export default function Home() {

  const { loading, error, data, refetch } = useQuery(GET_SNAPSHOT,{
    variables:{
      pairAddress:"0xbc9d21652cca70f54351e3fb982c6b5dbe992a22"
    }
  });

  if (loading) return 'Loading...';
  if (error) return `Error! ${error.message}`;


  console.log(data)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Hello world
      </div>
    </>
  )
}
