version: '3.8'

services:
  backend:
    build: ./backend-into
    container_name: backend-into
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=1234
      - DB_NAME=snapshots
      - DB_PORT=5432
    ports:
      - '4000:4000'
    depends_on:
      - db

  frontend:
    build: ./frontend-into
    container_name: frontend-into
    ports:
      - '3000:3000'

  db:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=snapshots
    ports:
      - '5478:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
